### ISSUE TITLE
wrong permission to Logfile

### ISSUE THREAD

**Issue by bodsch** [bodsch/docker-icinga2#4]
```
/usr/local/lib/logging.rb:24:in `initialize': Permission denied @ rb_sysopen - /tmp/monitoring.log (Errno::EACCES)
from /usr/local/lib/logging.rb:24:in `open'
	from /usr/local/lib/logging.rb:24:in `configure_logger_for'
	from /usr/local/lib/logging.rb:18:in `logger_for'
	from /usr/local/lib/logging.rb:10:in `logger'
	from /usr/local/lib/icingachecks.rb:54:in `initialize'
	from /usr/lib/monitoring-plugins/check_cm_feeder_status:13:in `initialize'
	from /usr/lib/monitoring-plugins/check_cm_feeder_status:182:in `new'
	from /usr/lib/monitoring-plugins/check_cm_feeder_status:182:in `<main>'
```

**Comment by bodsch** [comment]
fixed with https://github.com/bodsch/ruby-icinga-cert-service/commit/6ff420913360ed9e702dba506d951c8ee030eca7
